### ISSUE TITLE
add wavelengths?

### ISSUE THREAD

**Issue by rterrien** [Thomaslund1/SpecCorrect#13]
https://github.com/Thomaslund1/SpecCorrect/blob/82d2b558f7d1e0eb0d3373c01db4e22da5106821/examples/graphByOrder.py#L27

Suggest adding a few lines to show how to get the wavelengths that could be used to define the x-axis for a plot of drift vs wavelength. 

Since I would expect this to be a common task, it may be reasonable to define a convenience function that returns the wavelengths

**Comment by Thomaslund1** [comment]
an example can be seen on spectral ruler under examples
