### ISSUE TITLE
getVels function producing strange extra lines in data?

### ISSUE THREAD

**Issue by Fos314** [Thomaslund1/SpecCorrect#9]
![image](https://github.com/user-attachments/assets/0c6d8b7b-5f6a-464a-9892-c5d3037115c0)
When I run the getVels code to bin the velocity data into quartiles by order I get the plots below that are a bit odd: 
![Figure 97](https://github.com/user-attachments/assets/7fde1263-23dc-4766-bd75-e27efe064368)
![Figure 95](https://github.com/user-attachments/assets/11883b00-c580-47e6-a14b-f1a7fb55670a)
![Figure 91](https://github.com/user-attachments/assets/755955f0-8848-476e-babf-77d039d5063e)
The weird line patterns above seems to get better as the order number decreases. I will perhaps try different binning types to see if all this noise goes away.

**Comment by rterrien** [comment]
I agree that is weird, and it looks like something is going wrong. I would first check if individual modes (no binning) show the same pattern. If so, then something is going weird in the linefits output or subtraction to define velocities. If not, then you know it's something about the binning/averaging.
